Mega.Garage.Persentation/Areas/OnSite/Controllers/ProductGroupsController.cs
using Mega.Garage.Logic.OnSite.ViewModel;
using Mega.Garage.Persistence.OnSite.Entities;
using Mega.Garage.Presentation.Controllers;
using System.Web.Mvc;
using Mega.Garage.Logic.OnSite.Services;
using Mega.Garage.Logic.Catalog.Services;
using System.Web;
using Mega.Garage.Logic.FileUpload.Services;
using ClosedXML.Extensions;

namespace Mega.Garage.Presentation.Areas.OnSite.Controllers
{
    public class ProductGroupsController : BaseController
    {

        public ActionResult Index(ProductGroupSearchViewModel parameters)
        {
            int CurrentPage = int.Parse(Request["p"] ?? "1");
            parameters.CurrentPage = CurrentPage;
            parameters.PageSize = 25;
            ViewBag.PageSize = parameters.PageSize;
            var productGroups = ProductGroupService.GetAllProductGroups(parameters);
            ViewBag.TotalRecords = productGroups.TotalRecords;
            return View(productGroups.Records);
        }

        public ActionResult Modify(int? id)
        {
            if (id != null && id > 0)
            {
                var productGroup = ProductGroupService.GetProductGroupById((int)id);
                if (productGroup == null)
                    return HttpNotFound();

                ViewBag.LandingPageId = new SelectList(LandingPageService.GetAllLandingPages(), "Id", "Title", productGroup.LandingPageId);
                ViewBag.SelectedCategoryId = new SelectList(CategoryService.GetAllCategories(), "Id", "Title", productGroup.SelectedCategoryId);
                return View(productGroup);
            }
            else
            {
                ViewBag.LandingPageId = new SelectList(LandingPageService.GetAllLandingPages(), "Id", "Title");
                ViewBag.SelectedCategoryId = new SelectList(CategoryService.GetAllCategories(), "Id", "Title");
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Modify(ProductGroup productGroup, HttpPostedFileBase fileThumbImagePath, HttpPostedFileBase fileImagePath)
        {
            ViewBag.LandingPageId = new SelectList(LandingPageService.GetAllLandingPages(), "Id", "Title", productGroup.LandingPageId);
            ViewBag.SelectedCategoryId = new SelectList(CategoryService.GetAllCategories(), "Id", "Title", productGroup.SelectedCategoryId);

            ProductGroup entity = null;
            if (productGroup.Id > 0)
                entity = ProductGroupService.GetProductGroupById(productGroup.Id);

            if (fileThumbImagePath != null)
            {
                var LogoFileData = UploadService.Upload(fileThumbImagePath);
                productGroup.ThumbImagePath = LogoFileData.FileData.ToString();
            }
            else if (productGroup.Id > 0)
            {
                productGroup.ThumbImagePath = entity.ThumbImagePath;
            }

            if (fileImagePath != null)
            {
                var LogoFileData = UploadService.Upload(fileImagePath);
                productGroup.ImagePath = LogoFileData.FileData.ToString();
            }
            else if (productGroup.Id > 0)
            {
                productGroup.ImagePath = entity.ImagePath;
            }

            if (productGroup.Id > 0)
                ProductGroupService.UpdateProductGroup(productGroup);
            else
                ProductGroupService.AddProductGroup(productGroup);

            return RedirectToAction("Index");
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ProductGroupService.DeleteProductGroup(id);
            return RedirectToAction("Index");
        }

        public ActionResult Report(ProductGroupSearchViewModel parameters)
        {
            parameters.CurrentPage = 1;
            parameters.PageSize = int.MaxValue;
            var productGroups = ProductGroupService.GetAllProductGroups(parameters);
            var report = ProductGroupService.GenerateExcelReport(productGroups.Records);

            using (var wb = report)
            {
                return wb.Deliver("BrandsReport.xlsx");
            }
        }
    }
}

Mega.Garage.Persentation/Areas/OnSite/Views/ProductGroups/Index.cshtml
@model IEnumerable<Mega.Garage.Persistence.OnSite.Entities.ProductGroup>
@{
    Layout = "~/Views/Shared/_List.cshtml";
}

<div class="theader add">
    <section class="content-header">
        <h1>گروه های محصول</h1>
        <div class="create-btn btn btn-success" data-toggle="modal" data-target="#exampleModalCenter" data-whatever="adsa" onclick="openModal('@Url.Action("Modify","ProductGroups")', 'گروه محصول جدید')">
            <span class="arrow-box">
                <i class="arrow vertical"></i>
                <i class="arrow horizontal"></i>
            </span>
            گروه محصول جدید
        </div>
    </section>
</div>

<section class="content" style="min-height:unset;">
    <form method="get">
        <div class="row">
            <div class="col">
                <div class="box box-info">
                    <div class="box-header with-border">
                        <div class="box-tools pull-right">
                            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                        </div>
                    </div>
                    <div class="box-body">
                        <div class="row text-right">
                            <div class="col-md-3 form-group">
                                <label>عنوان</label>
                                <input id="textTitle" type="text" name="Title" class=" form-control" value="" />
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <div class="form-group">
                                    <button type="submit" class="btn btn-info pull-left margin-r-5">جستجو کن</button>
                                    <button type="reset" class="btn btn-default pull-left">حذف فیلتر</button>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</section>

<section class="content">
    <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover ">
            <thead class="thead-dark">
                <tr>
                    <th style="width: 110px;">
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Title)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.EnglishTitle)
                    </th>
                    <th style="width: 120px;"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.ImagePreview(modelItem => item.ThumbImagePath, Size: 't')
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Title)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.EnglishTitle)
                        </td>
                        <td>
                            <a href="@Url.Action("Index","ProductGroupProducts", new { Id = item.Id })">
                                <i class="fa fa-list"></i>
                            </a>

                            <span class="card-btn" title="ویرایش" data-toggle="modal" data-target="#exampleModalCenter" data-whatever="adsa" onclick="openModal('@Url.Action("Modify","ProductGroups",new { id = @item.Id })' , 'ویرایش گروه محصول ')">
                                <i class='fa fa-edit'></i>
                            </span>

                            <span class="card-btn" title="حذف" data-toggle="modal" data-target="#exampleModalCenter" data-whatever="adsa" onclick="openModal('@Url.Action("Delete","ProductGroups",new { id = @item.Id })' , 'حذف گروه محصول')">
                                <i class="fa fa-trash"></i>
                            </span>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="row">
        @{
            int PageSize = (int)(ViewBag.PageSize);
            int TotalRecords = (int)(ViewBag.TotalRecords);

        }
        @Html.Pagger(TotalRecords, PageSize)
    </div>
</section>

Mega.Garage.Persentation/Areas/OnSite/Views/ProductGroups/Modify.cshtml
@model Mega.Garage.Persistence.OnSite.Entities.ProductGroup

@using (Html.BeginForm("Modify", "ProductGroups", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.IsActive)
    @Html.HiddenFor(model => model.CreatedBy)
    @Html.HiddenFor(model => model.CreatedDate)
    @Html.HiddenFor(model => model.IsActive)
    @Html.HiddenFor(model => model.RowVersion)
    <div class="form-wrapper">
        <div class="form-group col-md-6 col-sm-12">
            <div class="flex-column">
                <label for="label">
                    @Html.DisplayNameFor(model => model.Title)
                </label>
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group col-md-6 col-sm-12">
            <div class="flex-column">
                <label for="label">
                    @Html.DisplayNameFor(model => model.EnglishTitle)
                </label>
                @Html.EditorFor(model => model.EnglishTitle, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group col-sm-12">
            <div class="flex-column">
                <label for="label">
                    @Html.DisplayNameFor(model => model.Description)
                </label>
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group col-md-6 col-sm-12">
            <div class="flex-column">
                <label for="label">
                    @Html.DisplayNameFor(model => model.ThumbImagePath)
                </label>
                @Html.FileUpload(model => model.ThumbImagePath)
            </div>
        </div>

        <div class="form-group col-md-6 col-sm-12">
            <div class="flex-column">
                <label for="label">
                    @Html.DisplayNameFor(model => model.ImagePath)
                </label>
                @Html.FileUpload(model => model.ImagePath)
            </div>
        </div>

        <div class="form-group col-md-6 col-sm-12">
            <div class="d-flex flex-column">
                <label for="label">
                    @Html.DisplayNameFor(model => model.LandingPageId)
                </label>
                @Html.DropDownList("LandingPageId", null, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group col-md-6 col-sm-12">
            <div class="d-flex flex-column">
                <label for="label">
                    @Html.DisplayNameFor(model => model.SelectedCategoryId)
                </label>
                @Html.DropDownList("SelectedCategoryId", null, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group col-12">
            <div class="d-flex flex-column">
                <div class="custom-control custom-switch">
                    @Html.CheckBoxFor(model => model.ShowFullCategoryProducts, new
                    {
                       @class = "custom-control-input",
                       id = "custom-switch-show-full-category-products",
                       name = "ShowFullCategoryProducts"
                    })
                    <label class="custom-control-label" for="custom-switch-show-full-category-products">
                        @Html.DisplayNameFor(model => model.ShowFullCategoryProducts)
                    </label>
                </div>
            </div>
        </div>

    </div>
    <div class="form-detail">@Html.Partial("_Details")</div>

    <div class="modal-footer btn-wrapper">
        <button type="submit" class="btn btn-primary"> ذخیره</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">بستن</button>
    </div>
}