Mega.Garage.Persentation/Areas/OnSite/Controllers/LandingPagesController.cs
using Mega.Garage.Logic.OnSite.Services;
using Mega.Garage.Persistence.OnSite.Entities;
using Mega.Garage.Presentation.Controllers;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace Mega.Garage.Presentation.Areas.OnSite.Controllers
{
    public class LandingPagesController : BaseController
    {
        public ActionResult Index()
        {
            return View(LandingPageService.GetAllLandingPages().ToList());
        }

        public ActionResult Modify(int? id)
        {
            if (id != null)
            {
                LandingPage landingPage = LandingPageService.GetLandingPageById((int)id);
                if (landingPage == null)
                    return HttpNotFound();

                return View(landingPage);
            }
            else
            {
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Modify(LandingPage landingPage)
        {
            if (landingPage.Id > 0)
                LandingPageService.UpdateLandingPage(landingPage);
            else
                LandingPageService.AddLandingPage(landingPage);

            return RedirectToAction("Index");
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            LandingPageService.DeleteLandingPage(id);
            return RedirectToAction("Index");
        }
    }
}

Mega.Garage.Persentation/Areas/OnSite/Views/LandingPages/Index.cshtml
@model IEnumerable<Mega.Garage.Persistence.OnSite.Entities.LandingPage>

@{
    Layout = "~/Views/Shared/_List.cshtml";
}

<div class="theader add">
    <section class="content-header">
        <h1>صفحات هدف</h1>
        <div class="create-btn btn btn-success" data-toggle="modal" data-target="#exampleModalCenter" data-whatever="adsa" onclick="openModal('@Url.Action("Modify","LandingPages")', 'صفحه هدف جدید')">
            <span class="arrow-box">
                <i class="arrow vertical"></i>
                <i class="arrow horizontal"></i>
            </span>
            صفحه هدف جدید
        </div>
    </section>
</div>

<section class="content">
    <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover ">
            <thead class="thead-dark">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Title)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.EnglishTitle)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Url)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Title)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.EnglishTitle)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Url)
                        </td>
                        <td>
                            <span class="card-btn" title="ویرایش" data-toggle="modal" data-target="#exampleModalCenter" data-whatever="adsa" onclick="openModal('@Url.Action("Modify","LandingPages",new { id = @item.Id })' , 'ویرایش صفحه هدف ')">
                                <i class='fa fa-edit'></i>
                            </span>

                            <span class="card-btn" title="حذف" data-toggle="modal" data-target="#exampleModalCenter" data-whatever="adsa" onclick="openModal('@Url.Action("Delete","LandingPages",new { id = @item.Id })' , 'حذف صفحه هدف')">
                                <i class="fa fa-trash"></i>
                            </span>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</section>

Mega.Garage.Persentation/Areas/OnSite/Views/LandingPages/Modify.cshtml
@model Mega.Garage.Persistence.OnSite.Entities.LandingPage

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.IsActive)
    @Html.HiddenFor(model => model.CreatedBy)
    @Html.HiddenFor(model => model.CreatedDate)
    @Html.HiddenFor(model => model.IsActive)
    @Html.HiddenFor(model => model.RowVersion)

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group col-md-6 col-sm-12">
            <div class="flex-column">
                <label for="label">
                    @Html.DisplayNameFor(model => model.Title)
                </label>
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group col-md-6 col-sm-12">
            <div class="flex-column">
                <label for="label">
                    @Html.DisplayNameFor(model => model.EnglishTitle)
                </label>
                @Html.EditorFor(model => model.EnglishTitle, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group col-md-6 col-sm-12">
            <div class="flex-column">
                <label for="label">
                    @Html.DisplayNameFor(model => model.Url)
                </label>
                @Html.EditorFor(model => model.Url, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group col-md-6 col-sm-12">
            <div class="flex-column">
                <label for="label">
                    @Html.DisplayNameFor(model => model.Keywords)
                </label>
                @Html.EditorFor(model => model.Keywords, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group col-sm-12">
            <div class="flex-column">
                <label for="label">
                    @Html.DisplayNameFor(model => model.Description)
                </label>
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
            </div>
        </div>

    </div>
    <div class="form-detail">@Html.Partial("_Details")</div>

    <div class="modal-footer btn-wrapper">
        <button type="submit" class="btn btn-primary"> ذخیره</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">بستن</button>
    </div>
}