Mega.Garage.Persentation/Areas/Polling/Controllers/QuestionController.cs
using Mega.Garage.Logic;
using Mega.Garage.Logic.Polling.Services;
using Mega.Garage.Persistence.Polling.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mega.Garage.Presentation.Areas.Polling.Controllers
{
    public class QuestionController : Controller
    {
        // GET: Polling/Question
        public ActionResult Index(string fromDate, string toDate, int? surveyId, string title, string surveyTitle, string code, int? questionType, int? clientId)
        {
            DateTime? startDate = Common.DateUtility.TryGetDateTime(fromDate);
            DateTime? endDate = Common.DateUtility.TryGetDateTime(toDate);

            ViewBag.surveyId = new SelectList(QuestionService.GetAllSurveys(), "Id", "Title", surveyId ?? 0);
            int CurrentPage = int.Parse(Request["p"] ?? "1");
            ViewBag.PageSize = 25;
            PagedList<Question> survey = 
                QuestionService.GetAllQuestionsWithFilter(startDate, endDate, title, surveyId, code, questionType, clientId, CurrentPage, ViewBag.PageSize);
            ViewBag.TotalRecords = survey.TotalRecords;

            return View(survey.Records);
        }

        public ActionResult Modify(int? id)
        {
            if (id != null && id > 0)
            {
                var question = QuestionService.GetQuestionById((int)id);
                ViewBag.SurveyId = new SelectList(QuestionService.GetAllSurveys(), "Id", "Title", question.SurveyId);
                return View(question);
            }
            else
            {
                ViewBag.SurveyId = new SelectList(QuestionService.GetAllSurveys(), "Id", "Title");
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Modify(Persistence.Polling.Entities.Question question)
        {
            if (question.Id > 0)
                QuestionService.UpdateQuestion(question);
            else
                QuestionService.AddQuestion(question);

            return RedirectToAction("Index");
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            QuestionService.DeleteQuestion(id);
            return RedirectToAction("Index");
        }
    }
}

Mega.Garage.Persentation/Areas/Polling/Views/Question/Index.cshtml
@model IEnumerable<Mega.Garage.Persistence.Polling.Entities.Question>

@{
    Layout = "~/Views/Shared/_List.cshtml";
}
<div class="theader add">
    <section class="content-header">
        <h1 class="">لیست سوالات</h1>
        <div class="create-btn btn btn-success" data-toggle="modal" data-target="#exampleModalCenter" data-whatever="adsa" onclick="openModal('@Url.Action("Modify","Question")', 'سوال جدید')">
            <span class="arrow-box">
                <i class="arrow vertical"></i>
                <i class="arrow horizontal"></i>
            </span>
            سوال جدید
        </div>
    </section>
</div>
<section class="content" style="min-height:unset;">
    <form method="get">
        <div class="row">
            <div class="col">
                <div class="box box-info">
                    <div class="box-header with-border">
                        <div class="box-tools pull-right">
                            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                        </div>
                    </div>
                    <div class="box-body">
                        <div class="row text-right">
                            <div class="col-md-3 form-group">
                                <label>عنوان</label>
                                <input name="title" class="form-control" />
                            </div>
                            <div class="col-md-3 form-group">
                                <label>دسته بندی</label>
                                @Html.DropDownList("surveyId", null, "انتخاب کنید", htmlAttributes: new { @class = "form-control" })
                            </div>
                            <div class="col-md-2 form-group">
                                <label>از تاریخ</label>
                                <input type="text" class="form-control persian-date" name="startDate" />
                            </div>
                            <div class="col-md-2 form-group">
                                <label>تا تاریخ</label>
                                <input type="text" class="form-control persian-date" name="endDate" />
                            </div>

                            <div class="col-md-2 form-group">
                                <label>کد</label>
                                <input name="code" class="form-control" />
                            </div>

                        </div>
                        <div class="row">
                            <div class="col">
                                <div class="form-group">
                                    <button type="submit" class="btn btn-info pull-left margin-r-5">جستجو کن</button>
                                    <button type="reset" class="btn btn-default pull-left">حذف فیلتر</button>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</section>
<section class="content">
    <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover ">
            <thead class="thead-dark">
                <tr>
                    <th>@Html.DisplayNameFor(model => model.Title)</th>
                    <th>@Html.DisplayNameFor(model => model.Survey.Title)</th>
                    <th>@Html.DisplayNameFor(model => model.IsNegativeAnswerBetter)</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td class="text-right">@Html.DisplayFor(modelItem => item.Title)</td>
                        <td class="text-right">@Html.DisplayFor(modelItem => item.Survey.Title)</td>
                        <td class="text-right">@Html.DisplayForBoolean(item.IsNegativeAnswerBetter)</td>
                        <td>
                            <span class="card-btn" title="ویرایش" data-toggle="modal" data-target="#exampleModalCenter" data-whatever="adsa" onclick="openModal('@Url.Action("Modify","Question",new { id = @item.Id })' , 'ویرایش سوال')">
                                <i class='fa fa-edit'></i>
                            </span>
                            <span class="card-btn" title="حذف" data-toggle="modal" data-target="#exampleModalCenter" data-whatever="adsa" onclick="openModal('@Url.Action("Delete","Question",new { id = @item.Id })' , 'حذف سوال')">
                                <i class="fa fa-trash"></i>
                            </span>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="row">
        @{
            int PageSize = (int)(ViewBag.PageSize);
            int TotalRecords = (int)(ViewBag.TotalRecords);
        }
        @Html.Pagger(TotalRecords, PageSize)
    </div>
</section>

Mega.Garage.Persentation/Areas/Polling/Views/Question/Modify.cshtml
@model Mega.Garage.Persistence.Polling.Entities.Question

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-wrapper">
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.RowVersion)

        <div class="form-group col-md-12 col-sm-12">
            <div class="d-flex flex-column">
                <label for="label">
                    @Html.DisplayNameFor(model => model.Title)
                </label>
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group col-md-12 col-sm-12">
            <div class="d-flex flex-column">
                <label for="label">
                    @Html.DisplayNameFor(model => model.SurveyId)
                </label>
                @Html.DropDownList("SurveyId", null, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group col-md-12 col-sm-12">
            <div class="d-flex flex-column">
                <div class="custom-control custom-switch">
                    @Html.CheckBoxFor(model => model.IsNegativeAnswerBetter, new
               {
                   @class = "custom-control-input",
                   id = "IsNegativeAnswerBetter",
                   name = "IsNegativeAnswerBetter"
               })
                    <label class="custom-control-label" for="IsForWeb">@Html.DisplayNameFor(model => model.IsNegativeAnswerBetter)</label>
                </div>
            </div>
        </div>

    </div>
    <div class="form-detail">@Html.Partial("_Details")</div>

    <div class="modal-footer btn-wrapper">
        <button type="submit" class="btn btn-primary"> ذخیره</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">بستن</button>
    </div>
}