Mega.Garage.Client/Controllers/UserController.cs
using Mega.Garage.Client.Garage;
using Mega.Garage.Client.Models;
using Mega.Garage.Logic.Account.Services;
using Mega.Garage.Logic.Account.Servies;
using Mega.Garage.Logic.Account.ViewModel;
using Mega.Garage.Logic.Catalog.Services;
using Mega.Garage.Logic.Order.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Mega.Garage.Client.Controllers
{
    public class UserController : BaseController
    {
        private const string CookieName = "AUTH";
        // GET: User
        [HttpGet]
        [ActionName("Profile")]
        public ActionResult ProfileData()
        {
            var mobile = Common.Cryptography.Decrypt(Common.Cookie.ReadCookie("AUTH"));
            var customer = CustomerService.GetCustomerByMobile(mobile);
            ViewBag.CarGroup = CarGroupService.GetAllCarGroups().ToList();

            return View(customer);
        }

        [HttpGet]
        public ActionResult Register(string redirect)
        {
            TempData["Redirect"] = TempData["Redirect"] ?? redirect;
            ViewBag.NeedDisable = false;
            bool hasRegistrationCookie = Common.Cookie.IsCookieSet(CookieName);
            if (hasRegistrationCookie)
            {
                string CookieValue = Common.Cookie.ReadCookie(CookieName);
                if (!string.IsNullOrEmpty(CookieValue))
                {
                    if (Common.Cryptography.TryDecrypt(CookieValue, out string MobileNo))
                    {
                        if (Common.Validate.IsMobile(MobileNo))
                        {
                            return Redirect("/");
                        }
                    }
                }
            }
            return View();
        }

        [HttpPost]
        public ActionResult Register(string redirect, string mobile)
        {
            ViewBag.NeedDisable = false;
            if (string.IsNullOrEmpty(mobile))
                return ReturnException(new string[] { "وارد کردن شماره تلفن اجباری است." });

            if (mobile == "09357214976") // این برای شماره عابدی هارد کد شده که دیگه اس ام اس فرستاده نشه و مستقیم لاگین بشه
            {
                string EncryptedMobile = Common.Cryptography.Encrypt("09357214976");
                Common.Cookie.SetCookie(CookieName, EncryptedMobile);
                Session["MobileNo"] = "09357214976";

                if (!string.IsNullOrEmpty(redirect))
                    return Redirect(redirect);
                else
                    return Redirect("~/");
            }

            TempData["Redirect"] = redirect;
            try
            {
                OtpService.RegisterOtp(mobile);
                TempData["MobileNumber"] = mobile;
                TempData["Messages"] = new List<Message>() { new Message { Type = MessageType.Success, Content = "کد پیامک ارسال شده را در کادر زیر وارد کنید." } };
                TempData["Verify"] = true;
                ViewBag.NeedDisable = false;

                return View(new { redirect });
            }
            catch (Exception ex)
            {
                return ReturnException(ex);
            }
        }

        [HttpPost]
        public ActionResult Verify(OtpVerifyViewModel otpVerifyViewModel, string redirect)
        {
            TempData["Redirect"] = redirect ?? TempData["Redirect"];

            ViewBag.NeedDisable = false;
            TempData["MobileNumber"] = otpVerifyViewModel.Mobile;
            TempData["Verify"] = true;

            try
            {
                var verifyResult = OtpService.Verify(otpVerifyViewModel);
                if (verifyResult.Status == MegaStatus.Successfull)
                {
                    string EncryptedMobile = Common.Cryptography.Encrypt(otpVerifyViewModel.Mobile);
                    Common.Cookie.SetCookie(CookieName, EncryptedMobile);
                    Session["MobileNo"] = otpVerifyViewModel.Mobile;

                    if (!string.IsNullOrEmpty(TempData["Redirect"]?.ToString()))
                        return Redirect(TempData["Redirect"].ToString());
                    else
                        return Redirect("~/");
                }
                else
                {
                    return ReturnException(verifyResult.Messages, RedirectToAction("Register", new { redirect }));
                }
            }
            catch (Exception ex)
            {
                return ReturnException(ex, RedirectToAction("Register"));
            }
        }

        public ActionResult Archive()
        {
            if (!Common.Cookie.IsCookieSet(CookieName))
                return HttpNotFound();

            var mobileNumber = Common.Cryptography.Decrypt(Common.Cookie.ReadCookie(CookieName));
            var customer = CustomerService.GetCustomerByMobile(mobileNumber);
            List<Persistence.Order.Entities.Invoice> invoiceList = new List<Persistence.Order.Entities.Invoice>();

            if (customer != null)
                invoiceList = InvoiceService.GetInvoiceListByCusomerId(customer.Id).OrderByDescending(item => item.InvoiceDate).ToList();

            ViewBag.Customer = customer;
            return View(invoiceList);
        }

        public ActionResult Logout()
        {
            Common.Cookie.ExpireCookie(CookieName);
            Common.Cookie.ExpireCookie("Cart");
            Common.Cookie.ExpireCookie("Discount");

            return Redirect("/");
        }

    }
}

Mega.Garage.Client/Views/User/Archive.cshtml
@model List<Mega.Garage.Persistence.Order.Entities.Invoice>
@{
    ViewBag.Title = "سوابق سفارش";
    var customer = (Mega.Garage.Persistence.Order.Entities.Customer)ViewBag.Customer;
    List<Mega.Garage.Persistence.Order.Entities.InvoiceProcess> InvoiceProcessList = Mega.Garage.Logic.Order.Services.InvoiceService.GetAllInvoiceProcesses().ToList();
}


<div class="hero-wrap hero-bread" style="background-image: url('/theme/images/bg_6.jpg');">
    <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
            <div class="col-md-9 ftco-animate text-center">
                <h1 class="mb-0 bread">@ViewBag.Title</h1>
            </div>
        </div>
    </div>
</div>

<section class="ftco-section">
    <div class="container">
        @Html.Partial("_Messages")

        <div class="item">
            <table class="table table-striped">
                <thead class="thead-dark">
                    <tr>
                        <th style="width:120px;">شماره سفارش</th>
                        <th>تاریخ سفارش</th>
                        <th>نوع پرداخت</th>
                        <th>قیمت نهایی</th>
                        <th>توضیحات</th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        string PurchaseDate = Mega.Garage.Common.DateUtility.GetPersianDate(item.InvoiceDate);
                        <tr>
                            <td><a href="/reviewOrder/check/@item.OrderNumber" target="_blank">@item.OrderNumber</a></td>
                            <td>
                                <div style="padding:3px 0;line-height:15px;">
                                    @PurchaseDate
                                    <br />
                                    <span style="font-size:12px;color:silver">(@item.InvoiceDate.ToString("HH:mm:ss"))</span>
                                </div>
                            </td>
                            <td>
                                <div style="padding:3px 0;line-height:15px;">
                                    @item.PaymentType.Title
                                    <br />
                                    @if (item.IsPayed.GetValueOrDefault())
                                    {
                                        <span style="font-size:12px;color:green">(پرداخت شده)</span>
                                    }
                                    else
                                    {
                                        <span style="font-size:12px;color:orangered">(پرداخت نشده)</span>
                                    }
                                </div>
                            </td>
                            <td>@item.FinalPrice.Value.ToString("N0") ریال </td>
                            <td>@item.PaymentStatus</td>
                            <td>
                                @if (item.PaymentTypeId == 2 && !item.IsPayed.GetValueOrDefault())
                                {
                                    <a href="/ReviewOrder/Payment/@item.OrderNumber" class="btn btn-success">پرداخت</a>
                                }
                            </td>
                            <td>
                                <a href="/reviewOrder/check/@item.OrderNumber" target="_blank" class="btn btn-primary">مشاهده</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>

        <div class="row marg-t-35">
            <div class="col">
                @Html.Partial("_DealerList")
            </div>
        </div>
    </div>
</section>

Mega.Garage.Client/Views/User/Profile.cshtml
@model Mega.Garage.Persistence.Order.Entities.Customer

<div class="container" style="margin-top: 35px; margin-bottom: 30px">
    <div class="row justify-content-center">
        <div class="col col-md-4 ftco-animate">
            <div class="row">
                <label for="txtFirstName">نام</label>
                <input type="text" class="form-control" id="txtFirstName" value="@Model.FirstName" disabled />
            </div>
            <div class="row">
                <label for="txtLastName">نام خانوادگی</label>
                <input type="text" class="form-control" id="txtLastName" value="@Model.LastName" disabled />
            </div>
            <div class="row">
                <label for="txtMobile">تلفن همراه</label>
                <input type="text" class="form-control" id="txtMobile" value="@Model.Mobile" disabled />
            </div>
            <div class="row">
                <label for="cmbCarGroup">گروه خودرو</label>
                <select id="cmbCarGroup" class="form-control" name="CarGroup" disabled>
                    <option value="">..:: انتخاب کنید ::..</option>
                    @for (int i = 0; i < ViewBag.CarGroup.Count; i++)
                    {
                        <option value="@(ViewBag.CarGroup[i].Code)" @(Model.CarGroupCode == ViewBag.CarGroup[i].Code ? "selected" : "")>@(ViewBag.CarGroup[i].Title)</option>
                    }
                </select>
            </div>
        </div>
    </div>
</div>

Mega.Garage.Client/Views/User/Register.cshtml
@{
    ViewBag.Title = "ثبت نام";
}

<div class="hero-wrap hero-bread" style="background-image: url('/theme/images/bg_6.jpg');">
    <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
            <div class="col-md-9 ftco-animate text-center">
                <h1 class="mb-0 bread">ورود به سامانه</h1>
                <p class="breadcrumbs"><span class="mr-2"><a href="~/">فروش اینترنتی محصولات اسپیدی</a></span></p>
            </div>
        </div>
    </div>
</div>



<section class="ftco-section">

    <div class="text-center" style="margin-bottom: 20px;">
        <a id="lnkRegister" href="#">ثبت نام</a> / <a id="lnkHaveCode" href="#">کد دارم</a>
    </div>

    <div class="container">
        @Html.Partial("_Messages")

        @if ((bool)(ViewBag.NeedDisable))
        {
            <div class="alert alert-success">
                <a href="/landing/snapp" style="color: #333">مشاهده محصولات</a>
            </div>
        }
        @if (!ViewBag.NeedDisable)
        {
            <div class="row justify-content-center">
                <div id="containerRegister" class="col-xl-8 ftco-animate @((TempData["Verify"] == null || !(bool)TempData["Verify"]) ? "" : "d-none")">
                    @using (Html.BeginForm("Register", "User", FormMethod.Post))
                    {
                        <h3 class="mb-4 billing-heading">برای ورود به سامانه لطفا شماره همراه خود را وارد نمایید:</h3>
                        <input type="hidden" name="redirect" value="@TempData["Redirect"]" />
                        <div class="row align-items-end">
                            <div class="col-md-9">
                                <div class="form-group">
                                    <label for="txtRegisterMobile">شماره همراه</label>
                                    @{
                                        if ((bool)(ViewBag.NeedDisable))
                                        {
                                            <input id="txtRegisterMobile" disabled="disabled" value="@ViewBag.MobileNo" type="tel" class="form-control" name="mobile" />
                                        }
                                        else
                                        {
                                            <input id="txtRegisterMobile" autocomplete="off" type="tel" class="form-control" name="mobile" />
                                        }
                                    }
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    <button @((bool)ViewBag.NeedDisable ? "disabled=disabled" : "") class="btn btn-primary px-4 btn-site">دریافت کد</button>
                                </div>
                            </div>
                            <div class="w-100"></div>
                        </div>
                    }
                </div>
                <div id="containerHaveCode" class="col-xl-8 ftco-animate @((TempData["Verify"] != null && (bool)TempData["Verify"]) ? "" : "d-none")">
                    @using (Html.BeginForm("Verify", "User", FormMethod.Post))
                    {
                        <h3 class="mb-4 billing-heading">برای ورود به سامانه لطفا کد ارسال شده را وارد کنید:</h3>
                        <div class="row align-items-end">
                            <div class="col-md-5">
                                <input type="hidden" name="redirect" value="@TempData["Redirect"]" />
                                <div class="form-group">
                                    <label for="txtMobile">شماره همراه</label>
                                    <input id="txtMobile" @((bool)ViewBag.NeedDisable ? "disabled=disabled" : "") type="tel" class="form-control" name="Mobile" value="@TempData["MobileNumber"]" @(TempData["MobileNumber"] != null ? "readonly" : "") />
                                </div>
                            </div>
                            <div class="col-md-5">
                                <div class="form-group">
                                    <label for="txtCode">کد پیامک شده</label>
                                    <input id="txtCode" @((bool)ViewBag.NeedDisable ? "disabled=disabled" : "") autocomplete="off" type="tel" class="form-control" name="Code" />
                                </div>
                            </div>
                            <div class="col-md-2">
                                <div class="form-group">
                                    <button @((bool)ViewBag.NeedDisable ? "disabled=disabled" : "") class="btn btn-primary px-4 btn-site">ورود</button>
                                </div>
                            </div>
                            <div class="w-100"></div>
                        </div>
                    }
                </div>
            </div>
        }
    </div>
</section>
<!-- .section -->


@section Scripts {
    <script>

        $(document).ready(function () {
             if ('@ViewBag.RefId' != '') {
                 $('form[name=paymentForm]').submit();
            }
            $("#lnkRegister").on("click", function (event) {
                event.preventDefault();
                event.stopPropagation();
                $("#containerHaveCode").addClass("d-none");
                $("#containerRegister").removeClass("d-none");

                $(".container").find(".alert").remove();
            });

            $("#lnkHaveCode").on("click", function (event) {
                event.preventDefault();
                event.stopPropagation();
                $("#txtMobile").removeAttr("disabled");
                $("#containerHaveCode").removeClass("d-none");
                $("#containerRegister").addClass("d-none");

                $(".container").find(".alert").remove();
            });

        });

    </script>
}

Mega.Garage.Client/Views/User/Verify.cshtml
@{
    ViewBag.Title = "Verify";
}

<h2>Verify</h2>
@Html.Partial("_Messages")

@using (Html.BeginForm())
{
    <input type="tel" name="Mobile" class="form-control" value="@TempData["MobileNumber"]" maxlength="20" placeholder="تلفن همراه" />

    <input type="tel" name="Code" class="form-control" maxlength="5" placeholder="کد پیامک شده" />

    <input type="submit" class="btn btn-success" value="ورود" />
}